### ISSUE TITLE
"MIDI Channel" Blank

### ISSUE THREAD

**Issue by xuuxpedro** [Cantersoft/YTPMVE#29]
I try to use the program, but when I click in auto map outputs the MIDI Channel it's blank. 
![image](https://github.com/user-attachments/assets/e7dd59a4-49b2-45d4-9a6b-ca6d4ec24f12)

**Comment by xuuxpedro** [comment]
I closed and just give this error:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not find file 'C:\Users\ur2dr\AppData\Local\Temp\YTPMVE\settings.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at EntryPoint.FromVegas(Vegas vegas)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at ScriptPortal.Vegas.ScriptHost.ScriptManager.Run(Assembly asm, String className, String methodName)
   at ScriptPortal.Vegas.ScriptHost.RunScript(Boolean fCompileOnly)

**Comment by xuuxpedro** [comment]
Going more deep, I discovered more errors: 
![image](https://github.com/user-attachments/assets/d7490481-ae3e-4b66-9701-9379bf3cb0d2)

**Comment by Cantersoft** [comment]
Please send me the MIDI file. I need to see what types of MIDI files are making these problems occur so that I can troubleshoot.

**Comment by Cantersoft** [comment]
I eventually discovered and fixed the issue. Try the new release.
